name: hugobdedev # todo: find out more about docker configs to manage services configs

services:
  website:
    image: website
    build: ./hugobde.dev
    depends_on:
      - msgme
      - AAAAAAAA
      - blog_bob
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - ./hugobde.dev/static:/data/hugobde.dev:ro
      - ./misc/certs:/etc/ssl:ro

  msgme:
    image: msgme
    build: ./msgme
    expose:
      - "3000"
    restart: on-failure
    volumes:
      - ./misc/certs:/etc/ssl:ro

  AAAAAAAA:
    image: aaaaaaaa
    build: ./AAAAAAAA
    expose:
      - "5000"
    init: true
    restart: on-failure
    volumes:
      - ./blog:/blog:ro

  blog_bob:
    image: blog_bob
    build: ./blog_bob
    init: true
    restart: on-failure
    volumes:
      - ./blog:/blog:rw
      - ./hugobde.dev/blog_source:/blog_articles:ro
